### ISSUE TITLE
I think its a duplicate issue from #1 some blocks appaer in the air

### ISSUE THREAD

**Issue by quentin452** [TCLProject/Biome-ID-Extender#5]
![image](https://user-images.githubusercontent.com/42176772/223060059-13a195be-7825-49e8-aa52-e14985aa55f1.png)

Seed :  -2770571424344469181
Location :  -157 114 23

Mods lists: 

- Nevermine-Tslat-1.1.2
- Biome_ID_Extender_1.7.10-1.0a

logs : 

[latest.log](https://github.com/TCLProject/Biome-ID-Extender/files/10896048/latest.log)

fixed when disconnect and reconnect

to reproduce : 

1 : need to put id < 255 in biome (like I:"Greckon Biome ID"=350 in AoA.cfg)
2 : go to the seed and the location
3 : watch flying block
4 : restart the world , bug diseaper

**Comment by HRudyPlayZ** [comment]
The mod has been transfered into https://github.com/FalsePattern/EndlessIDs and is now unsupported.
It has been fixed there too. 
The issue doesn't look like a duplicate but it was known for a while now.
